apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-politicians-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
***
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-politicians
  namespace: default
spec:
  serviceName: postgres-politicians
  replicas: 1
  selector:
    matchLabels:
      app: postgres-politicians
  template:
    metadata:
      labels:
        app: postgres-politicians
    spec:
      containers:
        - name: postgres
          image: postgres:17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "politicians_db"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-politicians-pvc
***
apiVersion: v1
kind: Service
metadata:
  name: postgres-politicians
  namespace: default
spec:
  selector:
    app: postgres-politicians
  ports:
    - port: 5432
      targetPort: 5432
