apiVersion: apps/v1
kind: Deployment
metadata:
  name: sources-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sources-service
  template:
    metadata:
      labels:
        app: sources-service
        version: v1
    spec:
      containers:
        - name: sources-service
          image: sources-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
