apiVersion: apps/v1
kind: Deployment
metadata:
  name: politicians-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: politicians-service
  template:
    metadata:
      labels:
        app: politicians-service
        version: v1
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until nc -z postgres-politicians 5432; do echo "waiting for postgres-politicians"; sleep 2; done
              until nc -z kafka 9092; do echo "waiting for kafka"; sleep 2; done
      containers:
        - name: politicians-service
          image: politicians-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
